### PR TITLE
Additional code to allow explicit URLs instead of just slugs for the media files

### PR DESCRIPTION
**Pull request by douglaskastle**

### CODE REVIEW

**Comment by eteubert** [comment]
Would you mind rebasing this branch against the beta branch and force-push (or rebase the branch and create a new PR)? Then only your commits should appear in the history, making it cleaner.

**Comment by douglaskastle** [comment]
OK that **_should_** be a rebased branch, see how it looks

**Comment by douglaskastle** [comment]
If that still looks wonky, have have a whole new branch from beta and copied over the changed files.

**Comment by douglaskastle** [comment]
Actually still looks weird, closing this PR and opening a new one #1211

**Pull request closed without merging**
