### PR TITLE
Update chosen & chosen image

### PR DESCRIPTION
**Pull request by noplanman**
Update to chosen 1.4.2.
Make image chosen work with newer versions of chosen.
Modify the places where the images get loaded, to get a nicer resolution image.
(This commit should fix the issues #768 and #425)

Here's a picture of what it looks like now. (Using the social podcast settings as an example)
image-chosen

### CODE REVIEW

**Comment by noplanman** [comment]
Here's a picture of what it looks like now. (Using the social podcast settings as an example)
image-chosen

**Comment by eteubert** [comment]
Thanks, that looks good :) Will merge it before next release.
I should also take the time and only enqueue it when needed, not on every admin screen.

**Comment by noplanman** [comment]
That's a great idea! It's actually quite easy to do :blush: 
[Look :eyes:](https://github.com/gutobenn/wp-to-diaspora/blob/9f47c9f64294abae54f2e32c5bff5ac96d1c7f45/wp-to-diaspora.php#L197)

**Comment by eteubert** [comment]
Thanks! :smile: I created a new PR that is directed against the release branch. Closing here.

**Pull request closed without merging**
