### PR TITLE
feat: add API route to clear caches:

### PR DESCRIPTION
**Pull request by eteubert**
implements #1507

## TODO

- [ ] update API docs

### CODE REVIEW

**Review by dnkbln — CHANGES_REQUESTED** [review]
Es sieht alles gut aus. Ich würde die Klasse aber umbennen und WP_REST_Podlove_Tools_Controller nennen, damit wir keinen Namenskonflikt zum Podcast-API Controller bekommen.
Um die Erweiterung der Doku kümmere ich mich. Ich habe das JSON File schon angepasst. Bei mir lokal gibt es aber kaputte Links.

**Comment by skylogic004** [comment]
Thanks for implementing this! I tried your code and it works great, except for one small change I had to make. My user for making WordPress REST API calls has the "Editor" role, which doesn't get passed your permissions check (which checks for Administrator only). 

Otherwise, this is a good workaround; my code is smoothly publishing new episodes now :)

**Comment by eteubert** [comment]
Hab mich in git verheddert. Hier der neue PR: #1546

@skylogic004 Thanks for testing! I will change it to the editor role before releasing 👌

**Comment by skylogic004** [comment]
@eteubert The current version of tools.php now checks ` if (!current_user_can('manage_options'))` (i.e. only admins). Shouldn't this be `if (!current_user_can('edit_posts'))`? 

(because my user for making WordPress REST API calls has the "Editor" role, so I had to change this code to get it to work)

**Pull request closed without merging**
