### PR TITLE
Fixed issue with Cache URL and non-ascii characters

### PR DESCRIPTION
**Pull request by Loewe88**
Fixes issue described here: https://community.podlove.org/t/solved-kind-of-cover-art-disappears-caching-issue/478/10

Fixed it the hardcore approach, first converting everything to ASCII and then removing everything except letters, numbers "-" and "_".

### CODE REVIEW

**Comment by eteubert** [comment]
Untested, but it looks like this breaks if the filename contains spaces or äöüóoø etc., no?

**Comment by Loewe88** [comment]
Tested it with the Filename "Testepi öüósode · We Talk Games!" and it converted it to "testepi-ouosode-c2b7-we-talk-games" which works in my test installation.

**Comment by eteubert** [comment]
Ah, right, because the conversion only needs to work one-way, not two-way as with the episode slugs. Looks good then :) 👍

**Comment by eteubert** [comment]
Merged manually to 2.4.1 branch https://github.com/podlove/podlove-publisher/commit/2c71a9a435f7d56dfe5c9c309749e2e7dcf9efb5

**Pull request closed without merging**
